### ISSUE TITLE
Cannot read property 'length'

### ISSUE THREAD

**Issue by ChaosDMNS** [MillenniumEarl/YAM#159]
I get this error in the log files over and over again for every game. in version 2.5.7

Error: spawn C:\Users\kai\AppData\Local\Programs\yam\resources\app.asar\node_modules\cwebp-bin\vendor\cwebp.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-05-10 03:10:07.422] [error] Error 20307: _preparePreview -> this._compressGamePreview: Error: Uncaught TypeError: Cannot read property 'length' of undefined

I had some problems with the menu bar not going away even after I unticked dev mode. it kept popping up on restart. I fixed that by deleting the config.json and preferences. I also deleted the cache.

because the meny tab was open, the rest of the window got pushed down. and I had to scroll down every time I wanted to change page. annoying....

I don't know if these two bugs are related...

If I keep it at default window size and don't touch the dev switch again. it looks fine, and works fine. I'll just use F11 for fullscreen instead to see more.

So I don't really know if this error actually does anything bad or not.
But I figured I'd report it.

**Comment by MillenniumEarl** [comment]
Thank you! As for the error you find in the log file it is due to something that interferes with the compression of games covers, for the moment I ignored it because it does not impact in any way on the use of the manager (apart from clogging the log file).

I am also aware of the problem of the developer menu that does not disappear, I could not understand why it happens. Since, however, in a few months I will have to rewrite the application I decided to ignore it.

If you can help you, you can use the right and right arrows to move between the application pages.
