### ISSUE TITLE
Unable to Add Certain Games via URL

### ISSUE THREAD

**Issue by Satir12** [MillenniumEarl/YAM#223]
**Describe the bug**
When trying to add certain games, the program is unable to find them. When then proceeding to try and add them via URL it will popup with "Adding game from url" and then stop. I've noticed that this only happens on games with 0 reviews on f95. 

**To Reproduce**

1. Attempt to add a game with 0 reviews via URL
2. Choose the folder on computer
3. Input the url the game is located

**Comment by MillenniumEarl** [comment]
Hi @Satir12, thanks for the feedback!

I investigated the problem: this happens because some information about the game is present in a (hidden) field on the page that exists only in the presence of reviews.

This problem is actually the fault of the APIs ([here](https://github.com/MillenniumEarl/F95API)) that I have developed to extrapolate the data of the platform, an API that I have completely rewritten in the last few months.

Since I intend to rewrite YAM around September and the fix for this problem would take me some time (which unfortunately I don't have right now), I would recommend that you wait for someone to write a review on the game in question and then try to add it.

It is not exactly the best of solutions but right now it is the only thing that comes to me to suggest to you.
