### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by ChaosDMNS** [MillenniumEarl/YAM#270]
F95Zone now requires Captcha.. you need to add a way for us to solve the captcha in the program.

**Comment by MillenniumEarl** [comment]
Yes, I know.

I already fix the API ([here](https://github.com/MillenniumEarl/F95API)) and created a library for Captcha harvest ([here](https://github.com/MillenniumEarl/recaptcha-harvester)). Now I should only integrate the fixes in YAM.

This will take some time because the API changed is a new version and not the version currently used in YAM (I was preparing for the new YAM version that I was planning to develop in this month)

**Comment by MillenniumEarl** [comment]
Fixed in 2.6.0
