### ISSUE TITLE
path parsing options

### ISSUE THREAD

**Issue by CuddleBear92** [MillenniumEarl/YAM#378]
Could we get some options on the path parsing when importing or scanning folders?
For example being able to set our own setup, users have different setups from the past and importing titles in bulk would be swell.

For example i have a Game-List controlled collection that has all the titles installed like: `creator\title\version\game.exe`
Having the ability to change the parsed path to say that scheme or any other scheme would open up for more usecases across the board.

**Comment by CuddleBear92** [comment]
why was this closed? its still an issue.

**Comment by MillenniumEarl** [comment]
Forgive me, bot's fault

I thought I had already answered this Issue, in any case: the new version (which for reasons of force majeure goes slowly) uses a similar structure of the directories.

Since some features are added as versions management and mod/patch installation, "enter" in directories via Explorer could make more damage than anything else, so you need to access it only by application.

If the games must be moved (on HDD for example) I can implement an option to "extract" a certain version of the user's choice in some folder (in single or batch).
